### PR TITLE
Release/web/snowflake/1.0.1

### LINKED ISSUE #97: Snowflake web: Fix varchar length for yauaa columns
Currently there is a mismatch between how the model creates the yauaa varchar columns in and `derived.page_views` in comparison to `scratch.pv_page_view_events`. 

More specifically, the `page_views` table's yauaa columns specify a max length [here](https://github.com/snowplow/data-models/blob/847a2e686978e79bfed195d212d7676a6fe7f36d/web/v1/snowflake/sql-runner/sql/standard/02-page-views/01-main/00-setup-page-views.sql#L188-L205), according to the yauaa context schema [here](https://github.com/snowplow/iglu-central/blob/master/schemas/nl.basjes/yauaa_context/jsonschema/1-0-1). (Same for `sessions` table [here](https://github.com/snowplow/data-models/blob/847a2e686978e79bfed195d212d7676a6fe7f36d/web/v1/snowflake/sql-runner/sql/standard/03-sessions/01-main/00-setup-sessions.sql#L189-L208))

However, the `pv_page_view_events` does not follow so: [link](https://github.com/snowplow/data-models/blob/847a2e686978e79bfed195d212d7676a6fe7f36d/web/v1/snowflake/sql-runner/sql/standard/02-page-views/01-main/01-page-view-events.sql#L146-L188).

This may present as a problem that will prevent the commit steps from running. 
One option is to remove the varchar length constrains, consistent with the Redshift and BigQuery models.

### LINKED ISSUE #109: Snowflake web: Fix se_label column length in events_staged
At the moment, the Snowflake web model sets `se_label` column length to 1000: https://github.com/snowplow/data-models/blob/9bf46f3d08d0305ee23ac8146dfdf3468c5619ec/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/00-setup-base.sql#L176 (related to https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/134).

This prevents the commit step of base module to succeed when the `se_label` column is of 4096 length in `atomic.events`, which is now normally the case.

### LINKED ISSUE #120: Snowflake web: Fix logic in users_sessions_this_run to account for sparse data
This is an existing issue described here: #118 , I'm separating the Snowflake web related part of it in order to be able to track / close the partial fix.

### LINKED ISSUE #122: Snowflake web: Fix varchar length for pseudonymized fields
This is an existing issue described here: #121 , I'm separating the Snowflake web related part of it in order to be able to track / close the partial fix.

### LINKED ISSUE #123: Snowflake web: Remove start_date variable from users module
This is an existing issue described here: #71 , I'm separating the Snowflake web related part of it in order to be able to track / close the partial fix.

### LINKED ISSUE #124: Snowflake Web: Update copyright notices
2021 -> 2021-2022

### LINKED ISSUE #125: Snowflake web: Update column check stored procedure
Currently the `column_check` stored procedure which validates if there are mismatched columns between source and target tables does not handle the exceptions when the varchar field changes in size. Due to the column length changes in the upcoming release (1.0.1) it needs to be changed to both: 

1. warn users in case the incoming source varchar column is longer than the target varchar column
2. enable the update in case the target varchar column is longer than the source varchar column

### PR DESCRIPTION
**Pull request by agnes-kiss**
New Snowflake web data model release to fix the following issues:

Snowflake Web: Update column check stored procedure (Close #125)
Snowflake Web: Fix varchar length for pseudonymized fields (Close #122)
Snowflake Web: Remove start_date variable from users module (Close #123)
Snowflake Web: Update copyright notices (Close #124)
Snowflake Web: Fix logic in users_sessions_this_run to account for sparse data (Close #120)
Snowflake Web: Fix varchar length for yauaa columns (Close #97)
Snowflake Web: Fix se_label column length in events_staged (Close #109)

`pr_check` has been run, which passed.

The prepare for release still needs to be added and the release notes should contain the DDL for users to accommodate the new version with increased column lengths.

### CODE REVIEW

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 1]
```diff
@@ -89,12 +89,18 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+    throw "ERROR: Source table is missing column(s) which exist in target table.";
 
   } else {
+      for (var i = 0; i < targetColumns.length; i++) {
+        if (+targetColumnLengths[i] < +sourceColumnLengths[i]) {
+          throw "ERROR: varchar field in source column " + sourceColumns[i] + " is longer than varchar field in target column."
+        }
+      }
 
       var columnAdditions = sourceColumns.filter(notIncludedIn(targetColumns));
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Not sure you are using this anymore

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 2]
```diff
@@ -105,11 +111,13 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
               for (var i = 0; i < targetColumns.length; i++) {
                   if (targetColumns[i] !== sourceColumns[i]) {
-                      throw "ERROR: Can only migrate extra columns of the end of source"
+                      throw "ERROR: Can only migrate extra columns of the end of source."
                   }
               }
-              add_columns_to(TARGET_SCHEMA, TARGET_TABLE, columnAdditions.join(','));
-              return "ok.Columns added."
+              var pos = targetColumns.length + 1
+              var extraCols = list_extra_cols(SOURCE_SCHEMA,SOURCE_TABLE,delim, pos).split(delim);
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Do we need this extra function? Could we not take this from `sourceColumns `?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 3]
```diff
@@ -89,12 +89,18 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
   var delim = '~';
   var sourceColumns = list_cols_with_type(SOURCE_SCHEMA,SOURCE_TABLE,delim).split(delim);
   var targetColumns = list_cols_with_type(TARGET_SCHEMA,TARGET_TABLE,delim).split(delim);
+  var sourceColumnLengths = list_cols_with_length(SOURCE_SCHEMA,SOURCE_TABLE,delim).split(delim);
+  var targetColumnLengths = list_cols_with_length(TARGET_SCHEMA,TARGET_TABLE,delim).split(delim);
 
-  if (targetColumns.some(notIncludedIn(sourceColumns)) === true) {
-
-      throw "ERROR: Source table is missing column(s) which exist in target table.";
+  if (targetColumns.length > sourceColumns.length) {
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: I think I preferred the previous check. It seems slightly more robust than this.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 4]
```diff
@@ -89,12 +89,18 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
   var delim = '~';
   var sourceColumns = list_cols_with_type(SOURCE_SCHEMA,SOURCE_TABLE,delim).split(delim);
   var targetColumns = list_cols_with_type(TARGET_SCHEMA,TARGET_TABLE,delim).split(delim);
+  var sourceColumnLengths = list_cols_with_length(SOURCE_SCHEMA,SOURCE_TABLE,delim).split(delim);
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Not a huge fan of needing these extra helper functions and ultimately queries. I am wondering would be easier to return all the columns as an array of objects:

```SQL
with prep as (       
select
    column_name,
    ordinal_position,
    data_type,
    character_maximum_length,
    numeric_precision,
    numeric_scale,
    case 
      when isc.data_type='TEXT' then CONCAT(isc.column_name, ' VARCHAR(',isc.character_maximum_length, ')')
      when isc.data_type='NUMBER' then CONCAT(isc.column_name, ' NUMBER(', isc.numeric_precision, ',',isc.numeric_scale, ')')
      else CONCAT(isc.column_name, ' ', isc.data_type)
    end as column_definition

from information_schema.columns isc

where table_schema = upper('scratch')
and table_name = upper('page_views_staged_test_0')
order by ordinal_position
)
  
select arrayagg(object_construct(*)) within group (order by ordinal_position asc) from prep
```

This would mean we can remove `list_cols_with_length` altogether. You can then extract the info you need from each object without having to run more queries. What do you think?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 3 above)
Comment (bill-warner) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: I appreciate the previous approach would fail here if the varchar lengths mismatched but perhaps we can adapt `sourceColumns` and `targetColumns` to only include the column + data type.

**Review by bill-warner — COMMENTED** [review]
Good job on this. All the fixes look good. The only points I have around the stored procedure, which I think we could potentially clean up. We can catch up on this if you want

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 4 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for the valuable feedback, I agree that it could be cleaner. Just added a reworked stored procedure commit, similar to the mobile model, without helper functions.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 5]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
-          WHERE table_schema='` + sch + `'
-            AND table_name='` + tbl + `';`;
-
-      var res = snowflake.createStatement({sqlText: stmt}).execute();
-      res.next();
-      result = res.getColumnValue(1);
-
-      return result;
+  if (cols_with_varchar_issue !== '') {
+    throw "ERROR: field length for source varchar column(s) " + cols_with_varchar_issue + " is longer than the target."
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql:155]: I don't think this is actually printing the values from `cols_with_varchar_issue`

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 6]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+                                       binds: [SOURCE_SCHEMA, SOURCE_TABLE,TARGET_SCHEMA, TARGET_TABLE]}
+                                      ).execute();
+  res.next();
+
+  missing_in_source = res.getColumnValue(1);
+  missing_in_target = res.getColumnValue(2);
+  cols_with_varchar_issue = res.getColumnValue(3);
+  cols_to_add = res.getColumnValue(4);
+
+  if (missing_in_target > 1) {
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: This doesn't seem to align with the error message. Should this not be `missing_in_source > 0`?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 7]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+    ),
+
+  varchar_check AS (
+    SELECT listagg(
+          CASE WHEN T.character_maximum_length < s.character_maximum_length THEN s.column_name END
+          , ', ') WITHIN GROUP (ORDER BY s.ordinal_position) AS cols_with_varchar_issue
+    FROM target_data  t
+    LEFT JOIN SOURCE_data s
+    ON t.ordinal_position = s.ordinal_position AND t.column_name = s.column_name
+    WHERE t.ordinal_position>= s.ordinal_position),
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: What is the purpose of this filter? If we are joining on `ordinal_position` won't this always be true `t.ordinal_position == s.ordinal_position`?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 8]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+
+  type_check AS (
+    SELECT SUM(CASE WHEN s.column_name IS NULL THEN 1 ELSE 0 END) AS missing_in_source,
+          SUM(CASE WHEN t.column_name IS NULL THEN 1 ELSE 0 END) AS missing_in_target
+    FROM target_data  t
+    FULL OUTER JOIN SOURCE_data s
+    ON t.ordinal_position = s.ordinal_position AND T.data_type = s.data_type AND s.column_name = t.column_name
+    WHERE t.ordinal_position>= s.ordinal_position OR s.ordinal_position is null),
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Again slightly confused by this filter. What is its purpose?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 9]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
-      return result;
+  if (cols_with_varchar_issue !== '') {
+    throw "ERROR: field length for source varchar column(s) " + cols_with_varchar_issue + " is longer than the target."
   }
 
-  function notIncludedIn(arr) {
-      return function(elt) {
-        return ! arr.includes(elt);
-      };
+  if (missing_in_source > 0) {
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Think you might have mixed this up?!

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 10]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+    throw "ERROR: Can only migrate extra columns of the end of source"
   }
 
-  function add_columns_to(sch, tbl, cols) {
-      var alter_stmt = `ALTER TABLE ` + sch + `.` + tbl + ` ADD COLUMN ` + cols;
-      snowflake.createStatement({sqlText: alter_stmt}).execute();
+  if (cols_to_add !== '') {
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: I think it might be a bit clearer to use `missing_in_target > 0` here. WDYT?

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql [hunk 11]
```diff
@@ -86,74 +86,99 @@ CREATE OR REPLACE PROCEDURE {{.output_schema}}.column_check(SOURCE_SCHEMA VARCHA
...
+      ordinal_position,
+      character_maximum_length,
+      data_type
+    FROM information_schema.columns isc
+    where table_schema = UPPER(:3)
+    AND table_name = UPPER(:4)
+    ORDER BY ordinal_position
+    ),
+
+  varchar_check AS (
```
Comment (bill-warner) [inline web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: I am wondering if we simply take the script from [here](https://github.com/snowplow/data-models/blob/ba0d08c27b9f226bf467aaedeb64d9f7a54df128/mobile/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql#L117-L162)

And add after here:
https://github.com/snowplow/data-models/blob/ba0d08c27b9f226bf467aaedeb64d9f7a54df128/mobile/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql#L156

```SQL
LISTAGG(CASE WHEN tc.column_name IS NOT NULL AND sc.character_maximum_length > tc.character_maximum_length THEN sc.column_name END, ',') as cols_w_incompatible_char_limits
```

Does that get us the details you need?

**Review by bill-warner — COMMENTED** [review]
I like the thinking. I still have a few outstanding questions with the stored procedure and one potential means to simplify a bit. interested to get your thoughts. It may be that I glossing over some of the finer details.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 5 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql:155]: I retested it just now and for me it works, let's discuss it if you get a different outcome than expected:
image

Comment (bill-warner) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql:155]: Ah my bad I think I must have been looking at the latter part of the message.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 6 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Indeed, I changed that now.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 9 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Yes, changed, this, too.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 11 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Yes, it looks like it does. As agreed, to keep it in synch with the mobile model I have changed it according to the above.

**Review by bill-warner — APPROVED** [review]
LGTM. Well done. Assuming the `pr_check` passed validation with the latest changes then I think we are good. Last things to do:

* Squash the latter commits where needed.
* Fix the typo in this commit message: `Snowfalke web: Update column check stored procedure`
* Add prepare for release commit. You can see an example of what needs to be changed here: a41c728ee87f4be8f10b47bd6dc43798e37e113a. In short, update the model version in the GE expectation files, update the playbook's version number, update both CHANGELOGS

File: CHANGELOG [hunk 12]
```diff
@@ -1,3 +1,13 @@
+Snowflake Web Version 1.0.0 (2022-02-24)
```
Comment (bill-warner) [inline CHANGELOG]: I think the version number here is wrong

**Review by bill-warner — COMMENTED** [review]
Just one more correction I think

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 1 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for highlighting this. The code has been revised in a later commit so this became redundant.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 2 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for highlighting this. The code has been revised in a later commit so this became redundant.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 3 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for highlighting this. The code has been revised in a later commit so this became redundant.

File: CHANGELOG (hunk 12 above)
Comment (agnes-kiss) [reply CHANGELOG]: thanks, you this has been revised now.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 7 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for highlighting this. The code has been revised in a later commit so this became redundant.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 8 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Thank you for highlighting this. The code has been revised in a later commit so this became redundant.

File: web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql (hunk 10 above)
Comment (agnes-kiss) [reply web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql]: Good suggestion, this has been taken into consideration for the final commit.
